// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-PhpouyWjszF8-GYPoLIjHZmP2aG6RLY',
    appId: '1:395515894714:web:150f083414cb6bac591b83',
    messagingSenderId: '395515894714',
    projectId: 'chat-2dd68',
    authDomain: 'chat-2dd68.firebaseapp.com',
    storageBucket: 'chat-2dd68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYdz3xTPYOxDSg-8oLXB8nHQThs8YwYY',
    appId: '1:395515894714:android:de1b453cba3e43cc591b83',
    messagingSenderId: '395515894714',
    projectId: 'chat-2dd68',
    storageBucket: 'chat-2dd68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO1tpZifZPDV2KCg3Gf9Hn-sLUXiheFX4',
    appId: '1:395515894714:ios:68aa9ca98db8cde1591b83',
    messagingSenderId: '395515894714',
    projectId: 'chat-2dd68',
    storageBucket: 'chat-2dd68.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO1tpZifZPDV2KCg3Gf9Hn-sLUXiheFX4',
    appId: '1:395515894714:ios:68aa9ca98db8cde1591b83',
    messagingSenderId: '395515894714',
    projectId: 'chat-2dd68',
    storageBucket: 'chat-2dd68.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-PhpouyWjszF8-GYPoLIjHZmP2aG6RLY',
    appId: '1:395515894714:web:5d1ac5faea830eb4591b83',
    messagingSenderId: '395515894714',
    projectId: 'chat-2dd68',
    authDomain: 'chat-2dd68.firebaseapp.com',
    storageBucket: 'chat-2dd68.appspot.com',
  );
}
